### ISSUE TITLE
Error translating with unicode UTF-16

### ISSUE THREAD

**Issue by archenop** [Montvydas/translatesubs#1]
D:\IDM\RAR\lucky2>translatesubs 1.ass out.ass --to_lang en
Translating to "english".
Traceback (most recent call last):
  File "c:\users\archen\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\archen\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Archen\AppData\Local\Programs\Python\Python39\Scripts\translatesubs.exe\__main__.py", line 7, in <module>
  File "c:\users\archen\appdata\local\programs\python\python39\lib\site-packages\translatesubs\translatesubs.py", line 71, in main
    subs_manager = SubsManager(filename=subs_file)
  File "c:\users\archen\appdata\local\programs\python\python39\lib\site-packages\translatesubs\subs_manager.py", line 37, in __init__
    self.origin_subs = pysubs2.load(filename)
  File "c:\users\archen\appdata\local\programs\python\python39\lib\site-packages\pysubs2\ssafile.py", line 102, in load
    return cls.from_file(fp, format_, fps=fps, **kwargs)
  File "c:\users\archen\appdata\local\programs\python\python39\lib\site-packages\pysubs2\ssafile.py", line 153, in from_file
    text = fp.read()
  File "c:\users\archen\appdata\local\programs\python\python39\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
[1.zip](https://github.com/Montvydas/translatesubs/files/6219918/1.zip)

**Comment by Montvydas** [comment]
Ah, never expected anyone to use non utf-8... Just about to add an option to either specify the encoding manually or allow chardet to determine encoding automatically with: `--encoding auto`. However I tried translating your file and it might not work very well tbh, since foreign characters seem to have some trouble getting translated by google... I don't know exactly why, but you might have better luck with [this](www.subtitlestranslator.com) tool. Even if I copy the first sub text, it  isn't translated very well in google translate if you select japanese language (which seems to be the case?), try it [here](https://translate.google.com/?sl=ja&tl=en&text=%E6%9C%AC%E7%89%87%E5%AD%97%E5%B9%95%E7%94%B1SOSG%E5%AD%97%E5%B9%95%E5%9B%A2%E5%88%B6%E4%BD%9C%20%20%E4%BB%85%E4%BE%9B%E5%AD%A6%E4%B9%A0%E4%BA%A4%E6%B5%81%20%20%E5%88%B6%E5%93%81%E7%A6%81%E6%AD%A2%E7%94%A8%E4%BA%8E%E5%95%86%E4%B8%9A%E7%94%A8%E9%80%94&op=translate) yourself. While subtitlestranslator.com seem to translate it very well.. "The subtitles of this film are produced by the SOSG subtitle team only for learning and communication products and prohibited for commercial use". It seems like your subtitles consist of chinese + japanese text? I think my tool will not work very well for that... It is best used with single language only (unless it is just a couple of words and best if they are western language).

**Comment by Montvydas** [comment]
Pushed update, which fixed the observed problem.
