### ISSUE TITLE
probably internet issue

### ISSUE THREAD

**Issue by mikelin499** [Montvydas/translatesubs#11]
Hello，

it looks like i have internet connection issue. Could you please take a look at the error code? I use vpn in my country. it is good with deepl api, but won't work with your code. thanks a looooot.

Traceback (most recent call last):
File "C:\Users\49901\anaconda3\envs\whisper\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\49901\anaconda3\envs\whisper\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\49901\anaconda3\envs\whisper\Scripts\translatesubs.exe_main.py", line 7, in
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\translatesubs\main.py", line 93, in main
original, translated = translate(language_manager, separators_to_try(args.separator),
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\translatesubs\main.py", line 155, in translate
original, translated = language_manager.translate_text(pronounce_origin=pronounce_origin,
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\translatesubs\managers\language_manager.py", line 48, in translate_text
for trans in translated:
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\translatesubs\translators\googletrans.py", line 47, in translate
google_translated = GoogleTrans._do_translate(text, to_lang)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\translatesubs\translators\googletrans.py", line 85, in _do_translate
return translator.translate(text, dest=to_lang)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\googletrans\client.py", line 205, in translate
translated = self.translate(item, dest=dest, src=src, **kwargs)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\googletrans\client.py", line 210, in translate
data, response = self._translate(text, dest, src, kwargs)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\googletrans\client.py", line 108, in _translate
r = self.client.get(url, params=params)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 755, in get
return self.request(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 600, in request
return self.send(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 620, in send
response = self.send_handling_redirects(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 647, in send_handling_redirects
response = self.send_handling_auth(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 684, in send_handling_auth
response = self.send_single_request(request, timeout)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpx_client.py", line 714, in send_single_request
) = transport.request(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_sync\http_proxy.py", line 110, in request
return self._tunnel_request(
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_sync\http_proxy.py", line 214, in _tunnel_request
proxy_connection.start_tls(url[1], timeout)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_sync\connection.py", line 126, in start_tls
self.connection.start_tls(hostname, timeout)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_sync\http11.py", line 71, in start_tls
self.socket = self.socket.start_tls(hostname, self.ssl_context, timeout)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_backends\sync.py", line 49, in start_tls
wrapped = ssl_context.wrap_socket(
File "C:\Users\49901\anaconda3\envs\whisper\lib\contextlib.py", line 137, in exit
self.gen.throw(typ, value, traceback)
File "C:\Users\49901\anaconda3\envs\whisper\lib\site-packages\httpcore_exceptions.py", line 12, in map_exceptions
raise to_exc(exc) from None
httpcore._exceptions.ConnectTimeout: _ssl.c:1112: The handshake operation timed out

The blows are my code:
def translate_srt_google(filepath, input_lang="en", output_lang="zh-cn"):
    output_filepath = f"{os.path.splitext(filepath)[0]}_EN+{output_lang.upper()}.srt"
    try:
        # Constructing the command for translating and merging subtitles
        command = f"translatesubs {filepath} {output_filepath} --to_lang zh-cn --merge"
        # Executing the command using subprocess
        subprocess.run(command, check=True, shell=True)
        print("翻译双语字幕成功:", filepath)
        return True
    except subprocess.CalledProcessError as e:
        print("翻译字幕失败:", filepath)
        print("错误代码:", e)
        return False

**Comment by Montvydas** [comment]
Have you tried running in terminal: `translatesubs your_filepath out.srt --to_lang zh-cn --merge` with success?
